name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ '11', '17', '21', '25', '26-ea' ]
        architecture: [ 'x64' ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn package

      - name: Verify class file versions
        uses: pivovarit/verify-jar-action@v1.4.0
        with:
          java-version: '11'
